apiVersion: v1
imagePullSecrets:
- name: my-database-secret
- name: test-secret
- name: test-secret
- name: test-secret3
- name: test-secret4
kind: ServiceAccount
metadata:
  name: default
  namespace: test-sa-gitops
